name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.146.0'
          extended: true
          
      - name: Install PostCSS CLI
        run: npm install -g postcss-cli
          
      - name: Build
        run: |
          # For GitHub Pages with relative URLs, we need to set the correct baseURL
          # but use relativeURLs=true in the Hugo configuration
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)
          GITHUB_USER=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 1)
          
          if [ "$REPO_NAME" = "$GITHUB_USER.github.io" ]; then
            # User/organization site - root domain
            hugo --minify
          else
            # Project site - needs the subpath in baseURL
            hugo --minify --baseURL="/$REPO_NAME/"
          fi
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
